/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Encrypt.java
 *
 * Created on Apr 11, 2009, 2:57:26 AM
 */

package RSA;
import bigInt.*;
/**
 *
 * @author Anant
 */
public class Encrypt extends javax.swing.JFrame {

    /** Creates new form Encrypt */
    public Encrypt() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldM = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonEncrypt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelPublicKey = new javax.swing.JLabel();
        jTextFieldE = new javax.swing.JTextField();
        labelE = new javax.swing.JLabel();
        labeln1 = new javax.swing.JLabel();
        jTextFieldN = new javax.swing.JTextField();
        jTextFieldEncM = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Lucida Grande", 0, 20));
        Title.setText("RSA Encryption system");

        jLabel2.setText("Encrypted Message:");

        jLabel3.setText("Enter message here:");

        jButtonEncrypt.setText("Encrypt");
        jButtonEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncryptActionPerformed(evt);
            }
        });

        labelPublicKey.setText("Public Key:");

        labelE.setText("e = ");

        labeln1.setText("n = ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelPublicKey)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(labeln1)
                        .add(1, 1, 1)
                        .add(jTextFieldN, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(labelE)
                        .add(2, 2, 2)
                        .add(jTextFieldE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                .add(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(labelPublicKey)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelE)
                    .add(jTextFieldE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labeln1)
                    .add(jTextFieldN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Generate keys");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Encrypt");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Decrypt");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Quit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(265, 265, 265)
                        .add(Title))
                    .add(layout.createSequentialGroup()
                        .add(42, 42, 42)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jTextFieldM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 276, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 310, Short.MAX_VALUE)
                        .add(jButtonEncrypt)
                        .add(191, 191, 191))
                    .add(layout.createSequentialGroup()
                        .add(jTextFieldEncM, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(Title)
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(7, 7, 7))
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jButtonEncrypt)
                        .add(29, 29, 29))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(18, 18, 18)))
                .add(jTextFieldEncM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncryptActionPerformed
        // TODO add your handling code here:
        List e = new List();
        e = List.readlist(jTextFieldE.getText());
        List n1 = new List();
        n1 = List.readlist(jTextFieldN.getText());
        String m = jTextFieldM.getText();

        int N = List.length(n1);

  //      System.out.println("LenN= "+ N + " N= " +List.printlist(n1) + " Ntail = " + List.printlist(n1.tail()));

        int messageLength = m.length();
        char messageArray[] = m.toCharArray();
        int curlength = 0;
        List CurEncryptedMessage  = new List ();
        List FinalEncryptedMessage = new List();
        for(int x =0; x<messageLength;x++) {
            char currentChar = messageArray[x];
            int asciiVal = (int) currentChar;
            List currentAsciiList = new List();

         //   System.out.println(List.printlist(CurEncryptedMessage) + " curchar = " + currentChar + " asciiVal = " + asciiVal);

            currentAsciiList.attach(asciiVal%10);
            asciiVal /= 10;
            currentAsciiList.attach(asciiVal%10);
            asciiVal /= 10;
            if(asciiVal == 0) {
                currentAsciiList.attach(0);
            }
            else {
                currentAsciiList.attach(asciiVal%10);
                asciiVal /= 10;
            }

            currentAsciiList = currentAsciiList.reverse();

       //     System.out.println("currentAsciiList = " + List.printlist(currentAsciiList) + " char = " + currentChar + " asciiVal = " + asciiVal);

            if(curlength < N - 3) {
                CurEncryptedMessage = List.append(CurEncryptedMessage,currentAsciiList);
                curlength += 3;
           //     System.out.println("CurEncryptedMessage = " + List.printlist(CurEncryptedMessage) + " curlength = " + curlength + " N = " + N);

            }
            else {
                
                List encrypted = List.expmod(CurEncryptedMessage,e,n1);
                while(List.length(encrypted) != N)
                    encrypted.attach(0);
                FinalEncryptedMessage = List.append(encrypted,FinalEncryptedMessage);
                curlength = 3;
                CurEncryptedMessage = new List();
                CurEncryptedMessage = List.append(CurEncryptedMessage,currentAsciiList);
          //      System.out.println("CurEncryptedMessage = " + List.printlist(CurEncryptedMessage) + "FinalEncryptedMessage = " + List.printlist(FinalEncryptedMessage)+ " curlength = " + curlength + " Encrypted = " + List.printlist(encrypted));

            }

        }
        if(!CurEncryptedMessage.empty()) {
            List encrypted = List.expmod(CurEncryptedMessage,e,n1);
            while(List.length(encrypted) != N)
                    encrypted.attach(0);
            FinalEncryptedMessage = List.append( encrypted,FinalEncryptedMessage);
            curlength = 0;
            CurEncryptedMessage = new List();
         //   System.out.println("CurEncryptedMessage = " + List.printlist(CurEncryptedMessage) + "FinalEncryptedMessage = " + List.printlist(FinalEncryptedMessage)+ " curlength = " + curlength + " Encrypted = " + List.printlist(encrypted));

        }
            
        jTextFieldEncM.setText(List.printlist(FinalEncryptedMessage));
  //      System.out.println(List.length(FinalEncryptedMessage));

}//GEN-LAST:event_jButtonEncryptActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new RSA.Encrypt().setVisible(true);
}//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked

        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new RSA.Decrypt().setVisible(true);
}//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
}//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new RSA.About().setVisible(true);
}//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButtonEncrypt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldE;
    private javax.swing.JTextField jTextFieldEncM;
    private javax.swing.JTextField jTextFieldM;
    private javax.swing.JTextField jTextFieldN;
    private javax.swing.JLabel labelE;
    private javax.swing.JLabel labelPublicKey;
    private javax.swing.JLabel labeln1;
    // End of variables declaration//GEN-END:variables

}
