/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * keysGenerator.java
 *
 * Created on Apr 11, 2009, 3:40:07 AM
 */

package RSA;
import bigInt.*;
import java.util.Random;
/**
 *
 * @author Anant
 */
public class keysGenerator extends javax.swing.JFrame {

    /** Creates new form keysGenerator */
    public keysGenerator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        Generate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelPublicKey = new javax.swing.JLabel();
        jTextFieldE = new javax.swing.JTextField();
        labelE = new javax.swing.JLabel();
        labeln1 = new javax.swing.JLabel();
        jTextFieldN1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelPrivateKey = new javax.swing.JLabel();
        jTextFieldD = new javax.swing.JTextField();
        labelD = new javax.swing.JLabel();
        labeln2 = new javax.swing.JLabel();
        jTextFieldN2 = new javax.swing.JTextField();
        jLabelstatus1 = new javax.swing.JLabel();
        jLabelstatus2 = new javax.swing.JLabel();
        labelSizePrime = new javax.swing.JLabel();
        PrimeSize = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Lucida Grande", 0, 20));
        labelTitle.setText("RSA Key Generation system");

        Generate.setText("Generate");
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });
        Generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerateMouseClicked(evt);
            }
        });

        labelPublicKey.setText("Public Key:");

        labelE.setText("e = ");

        labeln1.setText("n = ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelPublicKey)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(labeln1)
                        .add(1, 1, 1)
                        .add(jTextFieldN1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(labelE)
                        .add(2, 2, 2)
                        .add(jTextFieldE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                .add(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(labelPublicKey)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelE)
                    .add(jTextFieldE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labeln1)
                    .add(jTextFieldN1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelPrivateKey.setText("Private Key:");

        labelD.setText("d = ");

        labeln2.setText("n = ");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelPrivateKey)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(labeln2)
                        .add(1, 1, 1)
                        .add(jTextFieldN2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(labelD)
                        .add(2, 2, 2)
                        .add(jTextFieldD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(labelPrivateKey)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelD)
                    .add(jTextFieldD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labeln2)
                    .add(jTextFieldN2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelSizePrime.setText("Enter the size of primes (5-100):");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Generate keys");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Encrypt");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Decrypt");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Quit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabelstatus1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 464, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(146, 146, 146)
                                        .add(Generate))
                                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(31, 31, 31))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelstatus2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 464, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .add(layout.createSequentialGroup()
                .add(91, 91, 91)
                .add(labelSizePrime)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(PrimeSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(144, 144, 144)
                .add(labelTitle)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(labelTitle)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelSizePrime)
                    .add(PrimeSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(Generate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(76, 76, 76)
                .add(jLabelstatus2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelstatus1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked
    private static boolean fermat_test(List p) {
        List a;
        Random randgen = new Random();
        a = List.randomList(randgen.nextInt(List.length(p)));
        return (List.isequal(List.expmod(a,p,p),a));
    }
    public static boolean isprime(List p, int q) {
        if(p.head() % 2 ==0)
        return false;
        else if (p.head()==5)
            return false;
        else if(List.sod(p)%3==0)
            return false;
        else {
            boolean failed = false;
            while (q != 0 & !failed) {
                failed = !fermat_test(p);
                q = q-1;
         //       System.out.println("Fermat test to be passed "+q+" more times");
            }
            if (q == 0)
                return true;
            else
                return false;
        }


    }
     
    private void GenerateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerateMouseClicked
        // TODO add your handling code here:
        
        List p = new List();
        List q = new List();

        Random randgen1 = new Random();
    //    jLabelstatus.setText("Generating prime p...");
        
        boolean flag = false;
        int accuracy = 10;
        int primesize = Integer.parseInt(PrimeSize.getText());

         while(!flag) {
            p = List.randomList(primesize + randgen1.nextInt( 3 ));
           
            p = p.clean();
        //    jLabelstatus2.setText("p = "+List.printlist(p));
            if (isprime(p,accuracy)) flag=true;
        }


   //     jLabelstatus.setText("Generating prime q...");
        Random randgen2 = new Random();
        flag =false;
    
        while(!flag) {
            q = List.randomList(primesize + randgen2.nextInt( 3 ));
            
            q = q.clean();
       //     jLabelstatus2.setText("q = "+List.printlist(q));
            if (isprime(q,accuracy)) flag=true;
        }
       
    //    List p = List.readlist(jTextFieldE.getText());
      //  List q = List.readlist(jTextFieldD.getText());
        
        
        
        

        //Calculating n
        List n=List.mult(p,q);
        jTextFieldN1.setText(List.printlist(n));
        jTextFieldN2.setText(List.printlist(n));
             
        
        //Calculating m
        List one = new List();
        one.attach(1);
        List two = new List();
        two.attach(2);
        List m = List.mult(List.sub(p, one),List.sub(q,one));

        flag = false;
        List e = new List();
        while(!flag) {
            e = List.randomList(3);
            e = e.clean();
            if (List.mod(e,two).clean().empty())
                flag = false;
            else {
                if (List.isequal(List.gcd(e, m), one))
                    flag = true;
                else
                    flag = false;

            }

        }
        jTextFieldE.setText(List.printlist(e));


        List d = List.inversemodm(e,m);
        jTextFieldD.setText(List.printlist(d));
        // generate p and q, two large primes



   //     jLabelstatus.setText("Idle.");

    }//GEN-LAST:event_GenerateMouseClicked

    private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new RSA.Encrypt().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new RSA.Decrypt().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new RSA.About().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new keysGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generate;
    private javax.swing.JTextField PrimeSize;
    private javax.swing.JLabel jLabelstatus1;
    private javax.swing.JLabel jLabelstatus2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldD;
    private javax.swing.JTextField jTextFieldE;
    private javax.swing.JTextField jTextFieldN1;
    private javax.swing.JTextField jTextFieldN2;
    private javax.swing.JLabel labelD;
    private javax.swing.JLabel labelE;
    private javax.swing.JLabel labelPrivateKey;
    private javax.swing.JLabel labelPublicKey;
    private javax.swing.JLabel labelSizePrime;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labeln1;
    private javax.swing.JLabel labeln2;
    // End of variables declaration//GEN-END:variables



}
